name: Deploy to Hugging Face Spaces

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config --global user.email "kawaiimidoriiro@gmail.com"
          git config --global user.name "Hachiru"

      - name: Push to Hugging Face Spaces
        run: |
          git clone https://huggingface.co/spaces/${{ secrets.HF_USERNAME }}/${{ github.event.repository.name }} hf_space
          rsync -av --exclude='.git' ./ hf_space/
          cd hf_space
          git add .
          git commit -m "Update from GitHub Actions"
          git push https://${{ secrets.HF_USERNAME }}:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/${{ secrets.HF_USERNAME }}/${{ github.event.repository.name }} main
